name: SLO Threshold Automation
on:
  pull_request:
    branches:
      - 'dev'
  push:
    branches:
      - 'master'
      - 'dev'
      - 'test/automation'

permissions:
  id-token: write
  security-events: write
  actions: read
  contents: write
  pull-requests: write

jobs:
  update-thresholds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: test/automation

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
          
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_CODEGURU_ROLE_ARN }}
          aws-region: ap-southeast-1
          role-session-name: 'slo-threshold-automation'

      - name: Process SLO Latency
        uses: haqimazhar/slo-threshold-automation@v0.0.1
        with:
          slo_config: ./config.yaml
      
      - name: list all files in the repository
        run: |
          cd slo-dashboard
          cat new-latency-slo.yaml


      # - name: Commit and Push Changes
      #   run: |
      #     git config user.name "github-actions"
      #     git config user.email "actions@github.com"
      #     git checkout master 
      #     git pull origin master
      #     git checkout -b update-thresholds
      #     git add template.yaml
      #     git commit -m "chore: update CloudFormation thresholds"
      #     git push origin update-thresholds

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: slo-threshold-automation
          branch-suffix: timestamp
          title: "[MASTER]: 🚀 Updated Workflows SLO Latency Thresholds"
          base: test/automation
          body: |
            ## 🎉 What's New?
            This PR updates the thresholds for workfloes Service Level Indicators (SLI) based on the latest available metric, ensuring optimized performance and reliability. 📊✨

            ### 🛠️ Key Changes
            - Updated SLO latency thresholds for each workflows .
            - Improved metrics configuration for better monitoring.

            ### ✅ Why is this important?
            These changes align with the latest SLO requirements and help maintain robust service level objectives.

            ### 🚀 Next Steps
            - [ ] Review the updated thresholds.
            - [ ] Merge the changes into `dev` for further testing.
            - [ ] Verify improvements in the monitoring dashboard.

            💬 If you have any questions or feedback, feel free to drop a comment below!
