name: SLO Threshold Automation
on:
  pull_request:
    branches:
      - 'dev'
  push:
    branches:
      - 'master'

permissions:
  id-token: write
  security-events: write
  actions: read
  contents: write
  pull-requests: write

jobs:
  update-thresholds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
          
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_CODEGURU_ROLE_ARN }}
          aws-region: ap-southeast-1
          role-session-name: 'slo-threshold-automation'

      - name: Process SLO Latency
        uses: haqimazhar/slo-threshold-automation@v0.0.1
        with:
          slo_config: ./config.yaml

      - name: list all files in the repository
        run: |
          cd slo-dashboard
          ls -la


      # - name: Commit and Push Changes
      #   run: |
      #     git config user.name "github-actions"
      #     git config user.email "actions@github.com"
      #     git checkout -b update-thresholds
      #     git add template.yaml
      #     git commit -m "chore: update CloudFormation thresholds"
      #     git push origin update-thresholds

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: update-thresholds
      #     title: "Update CloudFormation thresholds"
      #     body: "This PR updates thresholds for metrics based on the latest analytics data."
